import { createClient } from "@/lib/supabase/server";
import type {
  CustomerProfile,
  Conversation,
  Quote,
  Branch,
  BankingDetail,
  HdsPrice,
  Invoice,
  IntelligenceReport,
  HealthCheck,
  HealthComponentSummary,
  WaTemplate,
  BroadcastSegment,
  BroadcastCampaign,
  BroadcastRecipient,
  Segment,
  SegmentFilterRules,
  AiTestRun,
  AiTestRunSummary,
  AiQualityMetrics,
  ConversationSummary,
  ConversationQualityFlag,
  AiMonitorAlert,
  CustomerQuoteBreakdownMap,
  CustomerQuoteBreakdown,
  QuoteAcceptance,
  QuoteAcceptanceMap,
  UserWithRole,
  UserRole,
  Product,
} from "@/lib/types";
import { HEALTH_COMPONENT_ORDER, TEST_CATEGORY_ORDER } from "@/lib/constants";
import { createAdminClient } from "@/lib/supabase/admin";

export async function getDashboardStats() {
  const supabase = await createClient();

  const [customersRes, quotesRes, conversationsRes] = await Promise.all([
    supabase.from("customer_profiles").select("*").or("do_not_contact.is.false,do_not_contact.is.null"),
    supabase.from("quotes").select("total, created_at, status, source"),
    supabase
      .from("ai_conversations")
      .select("id, phone_number, sender_name, role, message_text, lead_status, created_at")
      .order("created_at", { ascending: false })
      .limit(10),
  ]);

  const customers = (customersRes.data || []) as CustomerProfile[];
  const quotes = (quotesRes.data || []) as Pick<
    Quote,
    "total" | "created_at" | "status" | "source"
  >[];
  const recentActivity = (conversationsRes.data || []) as Pick<
    Conversation,
    "id" | "phone_number" | "sender_name" | "role" | "message_text" | "lead_status" | "created_at"
  >[];

  // Split quotes by source for chatbot-first reporting
  const chatbotQuotes = quotes.filter((q) => q.source === "chatbot");

  // Chatbot-first metrics (primary)
  const chatbotRevenue = chatbotQuotes.reduce((sum, q) => sum + Number(q.total || 0), 0);

  // Customer-accepted quotes (derived from conversation analysis + lead stage).
  // Fetch full chatbot quote rows (need id/customer_phone/created_at/source)
  // and run the acceptance derivation used on the quotes page.
  const fullChatbotQuotes = await getChatbotQuotes();
  const acceptance = await getChatbotQuoteAcceptance(fullChatbotQuotes);
  const acceptedQuotes = fullChatbotQuotes.filter(
    (q) => acceptance[q.id]?.accepted
  );
  const acceptedQuotesCount = acceptedQuotes.length;
  const acceptedQuotesValue = acceptedQuotes.reduce(
    (sum, q) => sum + Number(q.total || 0),
    0
  );
  const activeLeads = customers.filter(
    (c) => c.lead_status !== "closed" && c.lead_status !== "lost"
  ).length;

  const now = new Date();
  const weekAgo = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);
  const chatbotQuotesThisWeek = chatbotQuotes.filter(
    (q) => new Date(q.created_at) >= weekAgo
  ).length;

  // Quote conversion rate = customer-accepted quotes / total chatbot quotes.
  // Measures what percentage of quotes generated by the chatbot were actually
  // accepted by customers (via message keyword or lead stage progression).
  const conversionRate =
    fullChatbotQuotes.length > 0
      ? Math.round((acceptedQuotesCount / fullChatbotQuotes.length) * 100)
      : 0;

  // Pipeline stages
  const pipeline = [
    "new",
    "quoting",
    "quoted",
    "closing",
    "objection",
    "follow_up",
    "handover",
    "closed",
  ].map((stage) => ({
    stage,
    count: customers.filter((c) => c.lead_status === stage).length,
  }));

  // Monthly revenue (last 6 months) — chatbot only
  const monthlyRevenue: { month: string; revenue: number }[] = [];
  for (let i = 5; i >= 0; i--) {
    const d = new Date(now.getFullYear(), now.getMonth() - i, 1);
    const monthEnd = new Date(now.getFullYear(), now.getMonth() - i + 1, 0);
    const monthName = d.toLocaleString("en-ZA", { month: "short" });
    const revenue = chatbotQuotes
      .filter((q) => {
        const qd = new Date(q.created_at);
        return qd >= d && qd <= monthEnd;
      })
      .reduce((sum, q) => sum + Number(q.total || 0), 0);
    monthlyRevenue.push({ month: monthName, revenue });
  }

  return {
    // Chatbot-first (primary metrics)
    totalRevenue: chatbotRevenue,
    activeLeads,
    quotesThisWeek: chatbotQuotesThisWeek,
    conversionRate,
    totalCustomers: customers.length,
    pipeline,
    monthlyRevenue,
    recentActivity,
    // Customer-accepted quotes (derived)
    acceptedQuotesCount,
    acceptedQuotesValue,
    totalQuotes: fullChatbotQuotes.length,
  };
}

export async function getCustomers(): Promise<CustomerProfile[]> {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from("customer_profiles")
    .select("*")
    .or("do_not_contact.is.false,do_not_contact.is.null")
    .order("last_interaction_at", { ascending: false, nullsFirst: false });
  if (error) throw error;
  return data as CustomerProfile[];
}

export async function getCustomerByPhone(
  phone: string
): Promise<CustomerProfile | null> {
  const supabase = await createClient();
  const normalized = phone.replace(/^\+/, "");
  const { data, error } = await supabase
    .from("customer_profiles")
    .select("*")
    .or(`phone_number.eq.${normalized},phone_number.eq.+${normalized}`)
    .maybeSingle();
  if (error) return null;
  return data as CustomerProfile;
}

/**
 * Build a per-customer quote breakdown (converted / pending / sent) by
 * merging two data sources:
 *
 *  1. `quotes` table joined with `invoices` — quotes that flowed through the
 *     Vercel quote engine and have a `customer_phone`. A quote is:
 *       - converted → has at least one paid invoice
 *       - pending   → has a pending invoice (no paid invoice)
 *       - sent      → no invoice yet
 *
 *  2. `ai_conversations` — quotes generated by the WhatsApp AI chatbot. Each
 *     distinct `quote_id` per phone represents one quote. These are
 *     categorised as "sent" unless the customer's `payment_status` on
 *     `customer_profiles` is `paid` (in which case one quote is marked
 *     converted) or `partial` / `pending` (one quote marked pending).
 *
 * Phone numbers are normalised by stripping a leading "+" so that
 * "+27123456789" and "27123456789" are treated as the same customer.
 */
export async function getCustomerQuoteBreakdown(): Promise<CustomerQuoteBreakdownMap> {
  const supabase = await createClient();

  // Fetch quotes that have a customer_phone, plus all invoices.
  const [quotesRes, invoicesRes, convRes, customersRes] = await Promise.all([
    supabase
      .from("quotes")
      .select("id, customer_phone, status")
      .not("customer_phone", "is", null),
    supabase.from("invoices").select("quote_id, status"),
    supabase
      .from("ai_conversations")
      .select("phone_number, quote_id")
      .not("quote_id", "is", null),
    supabase
      .from("customer_profiles")
      .select("phone_number, payment_status"),
  ]);

  const map: CustomerQuoteBreakdownMap = {};
  const ensure = (phone: string): CustomerQuoteBreakdown => {
    const key = phone.replace(/^\+/, "");
    if (!map[key]) {
      map[key] = { converted: 0, pending: 0, sent: 0, total: 0 };
    }
    return map[key];
  };

  // 1. Quotes table + invoices join
  const quotes = (quotesRes.data || []) as {
    id: string;
    customer_phone: string | null;
    status: string | null;
  }[];
  const invoices = (invoicesRes.data || []) as {
    quote_id: string | null;
    status: string | null;
  }[];

  // Build quote_id → invoice statuses
  const invoicesByQuote = new Map<string, string[]>();
  for (const inv of invoices) {
    if (!inv.quote_id) continue;
    const arr = invoicesByQuote.get(inv.quote_id) || [];
    arr.push(inv.status || "pending");
    invoicesByQuote.set(inv.quote_id, arr);
  }

  // Track which (phone, quote_id) pairs we've already counted from the quotes
  // table so we don't double-count them from ai_conversations.
  const countedFromQuotes = new Set<string>();

  for (const q of quotes) {
    if (!q.customer_phone) continue;
    const stats = ensure(q.customer_phone);
    const invStatuses = invoicesByQuote.get(q.id) || [];
    if (invStatuses.includes("paid")) {
      stats.converted += 1;
    } else if (invStatuses.includes("pending")) {
      stats.pending += 1;
    } else {
      stats.sent += 1;
    }
    stats.total += 1;
    countedFromQuotes.add(`${q.customer_phone.replace(/^\+/, "")}:${q.id}`);
  }

  // 2. AI conversations — count distinct quote_ids per phone
  const convs = (convRes.data || []) as {
    phone_number: string | null;
    quote_id: string | null;
  }[];
  const customers = (customersRes.data || []) as {
    phone_number: string | null;
    payment_status: string | null;
  }[];
  const paymentByPhone = new Map<string, string | null>();
  for (const c of customers) {
    if (c.phone_number) {
      paymentByPhone.set(c.phone_number.replace(/^\+/, ""), c.payment_status);
    }
  }

  // Distinct quote_ids per phone from conversations
  const aiQuotesByPhone = new Map<string, Set<string>>();
  for (const c of convs) {
    if (!c.phone_number || !c.quote_id) continue;
    const phone = c.phone_number.replace(/^\+/, "");
    if (!aiQuotesByPhone.has(phone)) {
      aiQuotesByPhone.set(phone, new Set());
    }
    aiQuotesByPhone.get(phone)!.add(c.quote_id);
  }

  for (const [phone, quoteIds] of aiQuotesByPhone) {
    const stats = ensure(phone);
    const paymentStatus = paymentByPhone.get(phone);
    let convertedFromAI = 0;
    let pendingFromAI = 0;
    if (paymentStatus === "paid") {
      convertedFromAI = 1; // at least one quote converted
    } else if (paymentStatus === "partial" || paymentStatus === "pending") {
      pendingFromAI = 1;
    }
    const sentFromAI = Math.max(0, quoteIds.size - convertedFromAI - pendingFromAI);
    stats.converted += convertedFromAI;
    stats.pending += pendingFromAI;
    stats.sent += sentFromAI;
    stats.total += quoteIds.size;
  }

  return map;
}

export async function getConversationsByPhone(
  phone: string,
  limit = 100
): Promise<Conversation[]> {
  const supabase = await createClient();
  const normalized = phone.replace(/^\+/, "");
  const { data, error } = await supabase
    .from("ai_conversations")
    .select("*")
    .or(`phone_number.eq.${normalized},phone_number.eq.+${normalized}`)
    .order("created_at", { ascending: true })
    .limit(limit);
  if (error) throw error;
  return data as Conversation[];
}

export async function getQuotesByPhone(
  phone: string
): Promise<Quote[]> {
  const supabase = await createClient();
  const normalized = phone.replace(/^\+/, "");
  const { data, error } = await supabase
    .from("quotes")
    .select("*")
    .or(`customer_phone.eq.+${normalized},customer_phone.eq.${normalized}`)
    .order("created_at", { ascending: false });
  if (error) throw error;
  return data as Quote[];
}

export async function getAllQuotes(source?: "chatbot" | "web" | "botsailor"): Promise<Quote[]> {
  const supabase = await createClient();
  let query = supabase
    .from("quotes")
    .select("*")
    .order("created_at", { ascending: false });
  if (source) {
    query = query.eq("source", source);
  }
  const { data, error } = await query;
  if (error) throw error;
  return data as Quote[];
}

/**
 * Get quotes generated by the new WhatsApp chatbot.
 * These are quotes with source = 'chatbot'.
 */
export async function getChatbotQuotes(): Promise<Quote[]> {
  return getAllQuotes("chatbot");
}

/**
 * Lead stages that indicate a chatbot quote was actually accepted by the
 * customer (handed over to sales / deal closed). Other stages ("quoting",
 * "quoted", "closing", "objection", "follow_up") reflect the AI working the
 * lead, not customer acceptance.
 */
const ACCEPTED_LEAD_STAGES = new Set(["handover", "closed"]);

/**
 * Phrases a customer is likely to use when accepting a quote. Kept deliberately
 * strong/positive to avoid flagging questions or objections as acceptance.
 */
const ACCEPTANCE_PHRASE_RE =
  /\b(accept(?:ed)?|approve[ds]?|confirm(?:ed)?|go ahead|let'?s do it|lets do it|let'?s go ahead|lets go ahead|i'?ll take it|ill take it|i will take it|sounds good|sounds great|let'?s proceed|lets proceed|proceed|i'?ll buy|ill buy|i will buy|book it|place the order|i'?ll order|ill order|i will order|i want to order|i'?ll pay|ill pay|i will pay|i can pay|make (?:the |a )?payment|i'?ll collect|ill collect|i will collect|i can collect|let'?s do that|lets do that|i want it|take it|count me in|i'?m in|im in)\b/i;

/**
 * Short standalone affirmatives (e.g. "yes", "yebo", "perfect"). Matched against
 * an anchored whitelist of complete messages so that "yes, where are you based?"
 * or "yes witbank/emalahleni" (answering a location question) are NOT counted as
 * acceptance — only unambiguous affirmative replies are.
 */
const SHORT_AFFIRMATIVE_RE =
  /^(yes|yebo|yeah|yep|yup|yes please|yes i will|yes ill|yes i can|yes that'?s fine|yes thats fine|yes it'?s fine|yes its fine|sure|sure thing|perfect|great|awesome|will do|let'?s do it|lets do it|go ahead|count me in|i'?m in|im in)\s*[!.?]*$/i;

function isShortAffirmative(text: string): boolean {
  const t = text.trim();
  if (t.length === 0 || t.length > 32) return false;
  return SHORT_AFFIRMATIVE_RE.test(t);
}

function messageIndicatesAcceptance(text: string | null | undefined): boolean {
  if (!text) return false;
  return ACCEPTANCE_PHRASE_RE.test(text) || isShortAffirmative(text);
}

/**
 * Derive a per-quote "customer accepted" indicator for chatbot quotes by
 * analysing the conversation history for each quote's customer.
 *
 * A quote is considered accepted if EITHER:
 *  (a) the customer sent a message after the quote was created whose text
 *      matches an acceptance phrase / short affirmative, OR
 *  (b) the customer's lead stage advanced to "handover" or "closed".
 *
 * This is a heuristic derived indicator — it does NOT mutate the quotes table.
 * Phone numbers are normalised by stripping a leading "+" so that
 * "+27123456789" (quotes.customer_phone) and "27123456789"
 * (ai_conversations.phone_number / customer_profiles.phone_number) match.
 */
export async function getChatbotQuoteAcceptance(
  quotes: Quote[]
): Promise<QuoteAcceptanceMap> {
  const result: QuoteAcceptanceMap = {};
  if (quotes.length === 0) return result;

  const supabase = await createClient();

  // Normalised phone → quotes (a customer may have several quotes)
  const phoneToQuotes = new Map<string, Quote[]>();
  const phones = new Set<string>();
  for (const q of quotes) {
    if (!q.customer_phone) continue;
    const phone = q.customer_phone.replace(/^\+/, "");
    if (!phone) continue;
    phones.add(phone);
    const arr = phoneToQuotes.get(phone) || [];
    arr.push(q);
    phoneToQuotes.set(phone, arr);
  }
  if (phones.size === 0) return result;

  const phoneList = Array.from(phones);

  // (a) Customer messages for these phones (role = 'user').
  //     Fetch all of them; we filter by created_at >= quote.created_at in JS.
  const [messagesRes, profilesRes] = await Promise.all([
    supabase
      .from("ai_conversations")
      .select("phone_number, message_text, created_at")
      .in("phone_number", phoneList)
      .eq("role", "user")
      .order("created_at", { ascending: true }),
    supabase
      .from("customer_profiles")
      .select("phone_number, lead_status")
      .in("phone_number", phoneList),
  ]);

  const messages = (messagesRes.data || []) as {
    phone_number: string | null;
    message_text: string | null;
    created_at: string;
  }[];
  const profiles = (profilesRes.data || []) as {
    phone_number: string | null;
    lead_status: string | null;
  }[];

  // phone → sorted customer messages (timestamps ascending)
  const messagesByPhone = new Map<string, { message_text: string | null; created_at: string }[]>();
  for (const m of messages) {
    if (!m.phone_number) continue;
    const phone = m.phone_number.replace(/^\+/, "");
    const arr = messagesByPhone.get(phone) || [];
    arr.push({ message_text: m.message_text, created_at: m.created_at });
    messagesByPhone.set(phone, arr);
  }

  // phone → lead stage accepted?
  const leadAcceptedByPhone = new Map<string, string | null>();
  for (const p of profiles) {
    if (!p.phone_number) continue;
    const phone = p.phone_number.replace(/^\+/, "");
    if (p.lead_status && ACCEPTED_LEAD_STAGES.has(p.lead_status)) {
      leadAcceptedByPhone.set(phone, p.lead_status);
    }
  }

  for (const [phone, phoneQuotes] of phoneToQuotes) {
    const customerMessages = messagesByPhone.get(phone) || [];
    const leadStage = leadAcceptedByPhone.get(phone) || null;
    const leadAccepted = leadStage !== null;

    for (const q of phoneQuotes) {
      const quoteTime = q.created_at;

      // (a) keyword scan of customer messages sent at/after the quote was created
      let keywordEvidence: string | null = null;
      for (const m of customerMessages) {
        if (m.created_at < quoteTime) continue;
        if (messageIndicatesAcceptance(m.message_text)) {
          keywordEvidence = (m.message_text || "").trim().slice(0, 120) || null;
          break;
        }
      }

      const keywordAccepted = keywordEvidence !== null;

      let accepted: boolean;
      let signal: QuoteAcceptance["signal"];
      let evidence: string | null;

      if (keywordAccepted && leadAccepted) {
        accepted = true;
        signal = "both";
        evidence = `"${keywordEvidence}" (lead: ${leadStage})`;
      } else if (keywordAccepted) {
        accepted = true;
        signal = "keyword";
        evidence = `"${keywordEvidence}"`;
      } else if (leadAccepted) {
        accepted = true;
        signal = "lead_status";
        evidence = `Lead stage: ${leadStage}`;
      } else {
        accepted = false;
        signal = null;
        evidence = null;
      }

      result[q.id] = { accepted, signal, evidence };
    }
  }

  return result;
}

/**
 * Derive the customer-acceptance indicator for a single quote. Intended for the
 * quote detail page. Non-chatbot quotes always return a non-accepted indicator
 * (the derivation is chatbot-specific).
 */
export async function getQuoteAcceptance(
  quote: Quote
): Promise<QuoteAcceptance> {
  if (quote.source !== "chatbot") {
    return { accepted: false, signal: null, evidence: null };
  }
  const map = await getChatbotQuoteAcceptance([quote]);
  return (
    map[quote.id] || { accepted: false, signal: null, evidence: null }
  );
}

/**
 * Get historical (pre-chatbot) quotes for the historical reporting section.
 * These are quotes with source = 'botsailor' or 'web' (legacy system).
 */
export async function getHistoricalQuotes(): Promise<Quote[]> {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from("quotes")
    .select("*")
    .in("source", ["botsailor", "web"])
    .order("created_at", { ascending: false });
  if (error) throw error;
  return data as Quote[];
}

export async function getQuoteById(id: string): Promise<Quote | null> {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from("quotes")
    .select("*")
    .eq("id", id)
    .maybeSingle();
  if (error) throw error;
  return data as Quote | null;
}

/**
 * Build the public PDF URL for a quote.
 *
 * Quote PDFs are stored in the Supabase Storage `hdsquotes` bucket, named
 * after the quote's `filename` column (e.g. "Q-20260817-7450-HDSWALT").
 * The `cutlist_url` column on the quotes table is unreliable (usually null),
 * so we construct the URL from the bucket + filename instead.
 */
export function getQuotePdfUrl(quote: Pick<Quote, "filename" | "cutlist_url">): string | null {
  if (quote.cutlist_url) return quote.cutlist_url;
  if (!quote.filename) return null;
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
  if (!supabaseUrl) return null;
  return `${supabaseUrl}/storage/v1/object/public/hdsquotes/${encodeURIComponent(quote.filename)}`;
}

export async function getBranches(): Promise<Branch[]> {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from("branches")
    .select("*")
    .order("trading_as", { ascending: true });
  if (error) throw error;
  return data as Branch[];
}

export async function getBankingDetails(): Promise<BankingDetail[]> {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from("banking_details")
    .select("*")
    .order("fx_branch", { ascending: true });
  if (error) throw error;
  return data as BankingDetail[];
}

export async function getPrices(): Promise<HdsPrice[]> {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from("hds_prices")
    .select("*")
    .order("description", { ascending: true });
  if (error) throw error;
  return data as HdsPrice[];
}

export async function getInvoices(): Promise<Invoice[]> {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from("invoices")
    .select("*")
    .order("created_at", { ascending: false });
  if (error) throw error;
  return data as Invoice[];
}

/**
 * Get invoices linked to chatbot quotes only.
 *
 * Invoices don't have a `source` column, so we join via quote_number to
 * quotes where source = 'chatbot'. This excludes legacy web/botsailor
 * invoices (which have phone numbers but are old test/production data
 * from the pre-chatbot era).
 */
export async function getChatbotInvoices(): Promise<Invoice[]> {
  const supabase = await createClient();
  // Step 1: fetch chatbot quote numbers
  const { data: chatbotQuotes, error: quoteError } = await supabase
    .from("quotes")
    .select("quote_number")
    .eq("source", "chatbot");
  if (quoteError) throw quoteError;
  const quoteNumbers = (chatbotQuotes || []).map((q) => q.quote_number).filter(Boolean);
  if (quoteNumbers.length === 0) return [];
  // Step 2: fetch invoices matching those quote numbers
  const { data, error } = await supabase
    .from("invoices")
    .select("*")
    .in("quote_number", quoteNumbers)
    .order("created_at", { ascending: false });
  if (error) throw error;
  return data as Invoice[];
}

export async function getIntelligenceReports(
  days = 30
): Promise<IntelligenceReport[]> {
  const supabase = await createClient();
  const dateFrom = new Date(
    Date.now() - days * 24 * 60 * 60 * 1000
  ).toISOString();
  const { data, error } = await supabase
    .from("intelligence_reports")
    .select("*")
    .gte("report_date", dateFrom.split("T")[0])
    .order("created_at", { ascending: false });
  if (error) throw error;
  return data as IntelligenceReport[];
}

export async function getIntelligenceStats() {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from("intelligence_reports")
    .select("category, severity, report_date, conversation_count");
  if (error) throw error;

  const reports = data || [];
  const total = reports.length;

  const byCategory = (
    [
      "ai_quality",
      "competitor",
      "pricing",
      "product_demand",
      "industry_trend",
    ] as const
  ).map((cat) => ({
    category: cat,
    count: reports.filter((r) => r.category === cat).length,
  }));

  const bySeverity = (["info", "warning", "critical"] as const).map((sev) => ({
    severity: sev,
    count: reports.filter((r) => r.severity === sev).length,
  }));

  const today = new Date();
  const last7 = new Date(today.getTime() - 7 * 24 * 60 * 60 * 1000)
    .toISOString()
    .split("T")[0];
  const recentCount = reports.filter(
    (r) => r.report_date >= last7
  ).length;

  return {
    total,
    byCategory,
    bySeverity,
    recentCount,
  };
}

// ============================================================================
// Phase 3 — System Health Monitoring
// ============================================================================

/**
 * Get the latest health check for each component, plus 30-day uptime stats.
 * Returns one summary row per component, ordered by HEALTH_COMPONENT_ORDER.
 */
export async function getHealthSummary(): Promise<HealthComponentSummary[]> {
  const supabase = await createClient();

  const thirtyDaysAgo = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString();

  // Fetch all checks from the last 30 days — we compute summaries client-side
  // to avoid needing Postgres window functions over the anon key.
  const { data, error } = await supabase
    .from("system_health_checks")
    .select("id, component, check_name, status, latency_ms, message, details, checked_at")
    .gte("checked_at", thirtyDaysAgo)
    .order("checked_at", { ascending: false });

  if (error) throw error;

  const checks = (data || []) as HealthCheck[];

  // Group by component
  const byComponent = new Map<string, HealthCheck[]>();
  for (const c of checks) {
    const arr = byComponent.get(c.component) || [];
    arr.push(c);
    byComponent.set(c.component, arr);
  }

  // Build summaries for known components, plus any unknown ones that appear
  const allComponents = new Set<string>(HEALTH_COMPONENT_ORDER);
  for (const comp of byComponent.keys()) allComponents.add(comp);

  const summaries: HealthComponentSummary[] = [];

  for (const component of allComponents) {
    const compChecks = byComponent.get(component) || [];
    if (compChecks.length === 0) {
      summaries.push({
        component,
        status: "unknown",
        latency_ms: null,
        message: "No health checks recorded in the last 30 days",
        last_check_at: "",
        details: null,
        uptime_30d: 0,
        total_checks_30d: 0,
        healthy_checks_30d: 0,
        degraded_checks_30d: 0,
        down_checks_30d: 0,
      });
      continue;
    }

    const latest = compChecks[0]; // already sorted DESC by checked_at
    const total = compChecks.length;
    const healthy = compChecks.filter((c) => c.status === "healthy").length;
    const degraded = compChecks.filter((c) => c.status === "degraded").length;
    const down = compChecks.filter((c) => c.status === "down").length;
    // Uptime = (healthy + degraded) / total — degraded counts as "up but impaired"
    const uptime = total > 0 ? Math.round(((healthy + degraded) / total) * 100) : 0;

    summaries.push({
      component,
      status: latest.status,
      latency_ms: latest.latency_ms,
      message: latest.message,
      last_check_at: latest.checked_at,
      details: latest.details,
      uptime_30d: uptime,
      total_checks_30d: total,
      healthy_checks_30d: healthy,
      degraded_checks_30d: degraded,
      down_checks_30d: down,
    });
  }

  // Sort by the canonical component order
  const orderIndex = (comp: string) => {
    const idx = HEALTH_COMPONENT_ORDER.indexOf(
      comp as (typeof HEALTH_COMPONENT_ORDER)[number]
    );
    return idx === -1 ? HEALTH_COMPONENT_ORDER.length : idx;
  };
  summaries.sort((a, b) => orderIndex(a.component) - orderIndex(b.component));

  return summaries;
}

/**
 * Get recent failures (degraded or down) for the failure log table.
 */
export async function getRecentHealthFailures(
  limit = 20
): Promise<HealthCheck[]> {
  const supabase = await createClient();

  const { data, error } = await supabase
    .from("system_health_checks")
    .select("id, component, check_name, status, latency_ms, message, details, checked_at")
    .in("status", ["down", "degraded"])
    .order("checked_at", { ascending: false })
    .limit(limit);

  if (error) throw error;
  return (data || []) as HealthCheck[];
}

/**
 * Get the overall system status: the worst status across all components.
 */
export function getOverallSystemStatus(
  summaries: HealthComponentSummary[]
): "healthy" | "degraded" | "down" | "unknown" {
  if (summaries.length === 0) return "unknown";
  if (summaries.some((s) => s.status === "down")) return "down";
  if (summaries.some((s) => s.status === "degraded")) return "degraded";
  if (summaries.every((s) => s.status === "unknown")) return "unknown";
  return "healthy";
}

/**
 * Get the last N checks for a specific component — used for per-component
 * history / sparkline views.
 */
export async function getComponentHealthHistory(
  component: string,
  limit = 50
): Promise<HealthCheck[]> {
  const supabase = await createClient();

  const { data, error } = await supabase
    .from("system_health_checks")
    .select("id, component, check_name, status, latency_ms, message, details, checked_at")
    .eq("component", component)
    .order("checked_at", { ascending: false })
    .limit(limit);

  if (error) throw error;
  return (data || []) as HealthCheck[];
}

// ============================================================================
// Phase 5 — WhatsApp Templates & Broadcasts
// ============================================================================

export async function getWaTemplates(): Promise<WaTemplate[]> {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from("wa_templates")
    .select("*")
    .order("created_at", { ascending: false });
  if (error) throw error;
  return (data || []) as WaTemplate[];
}

export async function getWaTemplate(id: string): Promise<WaTemplate | null> {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from("wa_templates")
    .select("*")
    .eq("id", id)
    .single();
  if (error) return null;
  return data as WaTemplate;
}

export async function getApprovedWaTemplates(): Promise<WaTemplate[]> {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from("wa_templates")
    .select("*")
    .eq("status", "approved")
    .order("name", { ascending: true });
  if (error) throw error;
  return (data || []) as WaTemplate[];
}

export async function getBroadcastSegments(): Promise<BroadcastSegment[]> {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from("broadcast_segments")
    .select("*")
    .order("created_at", { ascending: false });
  if (error) throw error;
  return (data || []) as BroadcastSegment[];
}

export async function getBroadcastSegment(
  id: string
): Promise<BroadcastSegment | null> {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from("broadcast_segments")
    .select("*")
    .eq("id", id)
    .single();
  if (error) return null;
  return data as BroadcastSegment;
}

export async function getBroadcastCampaigns(): Promise<
  Array<BroadcastCampaign & { template_name: string | null; segment_name: string | null }>
> {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from("broadcast_campaigns")
    .select(
      "*, template:wa_templates(name), segment:broadcast_segments(name)"
    )
    .order("created_at", { ascending: false });
  if (error) throw error;

  return (data || []).map((row) => {
    const r = row as BroadcastCampaign & {
      template: { name: string } | null;
      segment: { name: string } | null;
    };
    return {
      ...r,
      template_name: r.template?.name ?? null,
      segment_name: r.segment?.name ?? null,
    };
  });
}

export async function getBroadcastCampaign(
  id: string
): Promise<
  (BroadcastCampaign & { template_name: string | null; segment_name: string | null }) | null
> {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from("broadcast_campaigns")
    .select(
      "*, template:wa_templates(name), segment:broadcast_segments(name)"
    )
    .eq("id", id)
    .single();
  if (error) return null;

  const r = data as BroadcastCampaign & {
    template: { name: string } | null;
    segment: { name: string } | null;
  };
  return {
    ...r,
    template_name: r.template?.name ?? null,
    segment_name: r.segment?.name ?? null,
  };
}

export async function getBroadcastRecipients(
  campaignId: string,
  limit = 200
): Promise<BroadcastRecipient[]> {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from("broadcast_recipients")
    .select("*")
    .eq("campaign_id", campaignId)
    .order("created_at", { ascending: true })
    .limit(limit);
  if (error) throw error;
  return (data || []) as BroadcastRecipient[];
}

export async function getBroadcastStats() {
  const supabase = await createClient();
  const [templatesRes, campaignsRes] = await Promise.all([
    supabase.from("wa_templates").select("status"),
    supabase.from("broadcast_campaigns").select(
      "status, total_recipients, sent_count, delivered_count, read_count, replied_count, failed_count"
    ),
  ]);

  const templates = (templatesRes.data || []) as Pick<WaTemplate, "status">[];
  const campaigns = (campaignsRes.data || []) as Pick<
    BroadcastCampaign,
    | "status"
    | "total_recipients"
    | "sent_count"
    | "delivered_count"
    | "read_count"
    | "replied_count"
    | "failed_count"
  >[];

  const templatesByStatus: Record<string, number> = {};
  for (const t of templates) {
    templatesByStatus[t.status] = (templatesByStatus[t.status] || 0) + 1;
  }

  const totals = campaigns.reduce(
    (acc, c) => ({
      total_recipients: acc.total_recipients + (c.total_recipients || 0),
      sent_count: acc.sent_count + (c.sent_count || 0),
      delivered_count: acc.delivered_count + (c.delivered_count || 0),
      read_count: acc.read_count + (c.read_count || 0),
      replied_count: acc.replied_count + (c.replied_count || 0),
      failed_count: acc.failed_count + (c.failed_count || 0),
    }),
    {
      total_recipients: 0,
      sent_count: 0,
      delivered_count: 0,
      read_count: 0,
      replied_count: 0,
      failed_count: 0,
    }
  );

  return {
    totalTemplates: templates.length,
    templatesByStatus,
    totalCampaigns: campaigns.length,
    totals,
  };
}

// ---- Phase 4: Lead Segmentation ----

export async function getSegments(): Promise<Segment[]> {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from("segments")
    .select("*")
    .order("name", { ascending: true });
  if (error) throw error;
  return (data || []) as Segment[];
}

export async function getSegment(id: string): Promise<Segment | null> {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from("segments")
    .select("*")
    .eq("id", id)
    .single();
  if (error) return null;
  return data as Segment;
}

/**
 * Apply segment filter rules to a list of customers (in-memory filtering).
 * This mirrors the filter_rules JSONB schema documented in the migration.
 */
export function applySegmentFilter(
  customers: CustomerProfile[],
  rules: SegmentFilterRules
): CustomerProfile[] {
  const now = Date.now();

  return customers.filter((c) => {
    // customer_type filter
    if (rules.customer_type && rules.customer_type.length > 0) {
      if (!rules.customer_type.includes(c.customer_type || "unknown")) {
        return false;
      }
    }

    // lead_status filter
    if (rules.lead_status && rules.lead_status.length > 0) {
      if (!rules.lead_status.includes(c.lead_status || "new")) {
        return false;
      }
    }

    // city filter (ILIKE — case-insensitive substring match)
    if (rules.city) {
      if (!c.city || !c.city.toLowerCase().includes(rules.city.toLowerCase())) {
        return false;
      }
    }

    // preferred_branch filter (ILIKE)
    if (rules.preferred_branch) {
      if (
        !c.preferred_branch ||
        !c.preferred_branch
          .toLowerCase()
          .includes(rules.preferred_branch.toLowerCase())
      ) {
        return false;
      }
    }

    // min_total_quote_value
    if (rules.min_total_quote_value !== undefined) {
      if (Number(c.total_quote_value || 0) < rules.min_total_quote_value) {
        return false;
      }
    }

    // min_total_quotes
    if (rules.min_total_quotes !== undefined) {
      if ((c.total_quotes || 0) < rules.min_total_quotes) {
        return false;
      }
    }

    // quoted_within_days
    if (rules.quoted_within_days !== undefined) {
      if (!c.last_quote_date) return false;
      const cutoff = now - rules.quoted_within_days * 24 * 60 * 60 * 1000;
      if (new Date(c.last_quote_date).getTime() < cutoff) {
        return false;
      }
    }

    // interacted_within_days
    if (rules.interacted_within_days !== undefined) {
      if (!c.last_interaction_at) return false;
      const cutoff =
        now - rules.interacted_within_days * 24 * 60 * 60 * 1000;
      if (new Date(c.last_interaction_at).getTime() < cutoff) {
        return false;
      }
    }

    // has_objections
    if (rules.has_objections === true) {
      if (!c.objections || c.objections.length === 0) {
        return false;
      }
    }

    // sale_outcome filter
    if (rules.sale_outcome && rules.sale_outcome.length > 0) {
      if (!rules.sale_outcome.includes(c.sale_outcome || "pending")) {
        return false;
      }
    }

    // payment_status filter
    if (rules.payment_status && rules.payment_status.length > 0) {
      if (!rules.payment_status.includes(c.payment_status || "none")) {
        return false;
      }
    }

    return true;
  });
}

/**
 * Get per-segment counts and conversion stats for the reports page.
 */
export async function getSegmentStats() {
  const supabase = await createClient();
  const [segmentsRes, customersRes] = await Promise.all([
    supabase.from("segments").select("*").order("name", { ascending: true }),
    supabase.from("customer_profiles").select("*"),
  ]);

  const segments = (segmentsRes.data || []) as Segment[];
  const customers = (customersRes.data || []) as CustomerProfile[];

  const stats = segments.map((seg) => {
    const matched = applySegmentFilter(customers, seg.filter_rules);
    const closed = matched.filter(
      (c) =>
        c.lead_status === "closed" ||
        c.lead_status === "handover" ||
        c.sale_outcome === "won"
    ).length;
    const lost = matched.filter(
      (c) => c.lead_status === "lost" || c.sale_outcome === "lost"
    ).length;
    const conversionRate =
      matched.length > 0
        ? Math.round((closed / matched.length) * 100)
        : 0;
    const totalQuoteValue = matched.reduce(
      (sum, c) => sum + Number(c.total_quote_value || 0),
      0
    );

    return {
      id: seg.id,
      name: seg.name,
      description: seg.description,
      count: matched.length,
      closed,
      lost,
      conversionRate,
      totalQuoteValue,
    };
  });

  return stats;
}

/**
 * Get customer type distribution with counts and conversion rates.
 */
export async function getCustomerTypeStats() {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from("customer_profiles")
    .select("customer_type, lead_status, sale_outcome, total_quote_value, classification_source");
  if (error) throw error;

  const customers = data || [];
  const types = ["carpenter", "bulk_buyer", "retail", "homeowner", "diy", "unknown"];

  return types.map((type) => {
    const matched = customers.filter((c) => c.customer_type === type);
    const closed = matched.filter(
      (c) =>
        c.lead_status === "closed" ||
        c.lead_status === "handover" ||
        c.sale_outcome === "won"
    ).length;
    const conversionRate =
      matched.length > 0
        ? Math.round((closed / matched.length) * 100)
        : 0;
    const totalQuoteValue = matched.reduce(
      (sum, c) => sum + Number(c.total_quote_value || 0),
      0
    );
    const bySource = {
      ai: matched.filter((c) => c.classification_source === "ai").length,
      backfill: matched.filter((c) => c.classification_source === "backfill").length,
      manual: matched.filter((c) => c.classification_source === "manual").length,
      unknown: matched.filter(
        (c) => !c.classification_source || c.classification_source === "unknown"
      ).length,
    };

    return {
      type,
      count: matched.length,
      closed,
      conversionRate,
      totalQuoteValue,
      bySource,
    };
  });
}

// ============================================================================
// Phase 2 — AI Performance Reporting
// ============================================================================

/**
 * Get recent test run summaries for the pass-rate trend chart.
 * Returns the most recent N run summaries, ordered oldest → newest for charting.
 * Filters out single-scenario runs (run_type=scenario) which are not
 * representative of overall performance and create noisy trend lines.
 */
export async function getAiTestRunSummaries(
  limit = 30
): Promise<AiTestRunSummary[]> {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from("ai_test_run_summaries")
    .select("*")
    .in("run_type", ["smoke", "category", "full"])
    .order("created_at", { ascending: false })
    .limit(limit);
  if (error) throw error;
  // Reverse for chronological chart order (oldest first)
  return ((data || []) as AiTestRunSummary[]).reverse();
}

/**
 * Get the latest test run summary (most recent run).
 * Prefers smoke runs (which cover all 9 core categories, 1 scenario each)
 * as they're the most representative of overall bot performance across
 * all conversation types. Falls back to category runs, then full, then any.
 */
export async function getLatestAiTestRunSummary(): Promise<AiTestRunSummary | null> {
  const supabase = await createClient();

  // Try smoke runs first (cover all categories, most representative)
  for (const runType of ["smoke", "category", "full"]) {
    const { data, error } = await supabase
      .from("ai_test_run_summaries")
      .select("*")
      .eq("run_type", runType)
      .order("created_at", { ascending: false })
      .limit(1)
      .single();
    if (!error && data) {
      return data as AiTestRunSummary;
    }
  }

  // Fall back to any run
  const { data, error } = await supabase
    .from("ai_test_run_summaries")
    .select("*")
    .order("created_at", { ascending: false })
    .limit(1)
    .single();
  if (error) return null;
  return data as AiTestRunSummary;
}

/**
 * Get individual scenario results for a specific run_id.
 */
export async function getAiTestRunsByRunId(
  runId: string
): Promise<AiTestRun[]> {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from("ai_test_runs")
    .select("*")
    .eq("run_id", runId)
    .order("category", { ascending: true })
    .order("scenario_id", { ascending: true });
  if (error) throw error;
  return (data || []) as AiTestRun[];
}

/**
 * Get recent failed test scenarios across all runs.
 * Used for the "Recent Failures" table on the AI Performance dashboard.
 */
export async function getRecentAiTestFailures(
  limit = 25
): Promise<AiTestRun[]> {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from("ai_test_runs")
    .select("*")
    .eq("passed", false)
    .order("created_at", { ascending: false })
    .limit(limit);
  if (error) throw error;
  return (data || []) as AiTestRun[];
}

/**
 * Get per-category pass rates aggregated across recent runs.
 * Returns one entry per category with total/passed/failed counts and pass rate.
 *
 * IMPORTANT: Only aggregates across runs that actually test each category.
 * Smoke runs cover all 9 core categories (1 scenario each), so they're the
 * most reliable source for cross-category comparison. Category runs only test
 * one category (e.g. 40 new_customer scenarios), so including them would
 * heavily skew the aggregation. We prefer smoke runs, falling back to any
 * run type if no smoke runs exist.
 */
export async function getAiTestCategoryStats(
  runsLimit = 5
): Promise<
  Array<{
    category: string;
    total: number;
    passed: number;
    failed: number;
    passRate: number;
    avgLatencyMs: number | null;
    runCount: number;
  }>
> {
  const supabase = await createClient();

  // Prefer smoke runs (they cover all core categories evenly).
  // Fall back to any run type if not enough smoke runs exist.
  let runIds: string[] = [];

  const { data: smokeRuns } = await supabase
    .from("ai_test_run_summaries")
    .select("run_id")
    .eq("run_type", "smoke")
    .order("created_at", { ascending: false })
    .limit(runsLimit);

  runIds = (smokeRuns || []).map((r) => r.run_id);

  // If fewer than 3 smoke runs, supplement with full runs
  if (runIds.length < 3) {
    const { data: fullRuns } = await supabase
      .from("ai_test_run_summaries")
      .select("run_id")
      .eq("run_type", "full")
      .order("created_at", { ascending: false })
      .limit(runsLimit - runIds.length);
    runIds = [...runIds, ...(fullRuns || []).map((r) => r.run_id)];
  }

  // If still no runs, fall back to any recent runs
  if (runIds.length === 0) {
    const { data: anyRuns } = await supabase
      .from("ai_test_run_summaries")
      .select("run_id")
      .order("created_at", { ascending: false })
      .limit(runsLimit);
    runIds = (anyRuns || []).map((r) => r.run_id);
  }

  if (runIds.length === 0) {
    return TEST_CATEGORY_ORDER.map((category) => ({
      category,
      total: 0,
      passed: 0,
      failed: 0,
      passRate: 0,
      avgLatencyMs: null,
      runCount: 0,
    }));
  }

  // Fetch all test runs for those run_ids
  const { data, error } = await supabase
    .from("ai_test_runs")
    .select("category, passed, latency_ms, run_id")
    .in("run_id", runIds);

  if (error) throw error;

  const runs = data || [];
  const contributingRunIds = new Set(runIds);

  // Build stats per category, including any categories with zero results
  const allCategories = new Set<string>(TEST_CATEGORY_ORDER);
  for (const r of runs) allCategories.add(r.category);

  return Array.from(allCategories).map((category) => {
    const catRuns = runs.filter((r) => r.category === category);
    const total = catRuns.length;
    const passed = catRuns.filter((r) => r.passed).length;
    const failed = total - passed;
    const passRate = total > 0 ? Math.round((passed / total) * 100) : 0;
    const latencies = catRuns
      .filter((r) => r.latency_ms != null)
      .map((r) => r.latency_ms as number);
    const avgLatencyMs =
      latencies.length > 0
        ? Math.round(latencies.reduce((a, b) => a + b, 0) / latencies.length)
        : null;
    // Count how many of the contributing runs actually tested this category
    const catRunIds = new Set(catRuns.map((r) => r.run_id));
    const runCount = Array.from(contributingRunIds).filter((id) =>
      catRunIds.has(id)
    ).length;
    return { category, total, passed, failed, passRate, avgLatencyMs, runCount };
  });
}

/**
 * Get latency distribution buckets for the most recent run.
 * Returns counts per latency bucket for histogram-style display.
 */
export async function getAiTestLatencyDistribution(
  runId?: string
): Promise<Array<{ bucket: string; count: number }>> {
  const supabase = await createClient();

  let query = supabase
    .from("ai_test_runs")
    .select("latency_ms")
    .not("latency_ms", "is", null);

  if (runId) {
    query = query.eq("run_id", runId);
  } else {
    // Use the latest non-scenario run (scenario runs have only 1 test,
    // which produces a useless single-bar histogram)
    const { data: latest } = await supabase
      .from("ai_test_run_summaries")
      .select("run_id")
      .in("run_type", ["smoke", "category", "full"])
      .order("created_at", { ascending: false })
      .limit(1)
      .single();
    if (!latest) {
      return [];
    }
    query = query.eq("run_id", latest.run_id);
  }

  const { data, error } = await query;
  if (error) throw error;

  const latencies = (data || []).map((r) => r.latency_ms as number);

  const buckets = [
    { bucket: "0-5s", min: 0, max: 5000, count: 0 },
    { bucket: "5-10s", min: 5000, max: 10000, count: 0 },
    { bucket: "10-20s", min: 10000, max: 20000, count: 0 },
    { bucket: "20-30s", min: 20000, max: 30000, count: 0 },
    { bucket: "30-45s", min: 30000, max: 45000, count: 0 },
    { bucket: "45s+", min: 45000, max: Infinity, count: 0 },
  ];

  for (const lat of latencies) {
    for (const b of buckets) {
      if (lat >= b.min && lat < b.max) {
        b.count++;
        break;
      }
    }
  }

  return buckets.map(({ bucket, count }) => ({ bucket, count }));
}

/**
 * Get scenario failure frequency — which scenarios fail most often across
 * recent runs. Helps identify persistently broken scenarios vs flaky ones.
 */
export async function getAiTestFailureFrequency(
  runsLimit = 10
): Promise<
  Array<{
    scenario_id: string;
    scenario_name: string | null;
    category: string;
    failCount: number;
    lastFailedAt: string;
  }>
> {
  const supabase = await createClient();

  // Get recent run_ids
  const { data: runData } = await supabase
    .from("ai_test_run_summaries")
    .select("run_id")
    .order("created_at", { ascending: false })
    .limit(runsLimit);

  const runIds = (runData || []).map((r) => r.run_id);
  if (runIds.length === 0) return [];

  const { data, error } = await supabase
    .from("ai_test_runs")
    .select("scenario_id, scenario_name, category, created_at")
    .eq("passed", false)
    .in("run_id", runIds)
    .order("created_at", { ascending: false });

  if (error) throw error;

  const runs = data || [];
  const byScenario = new Map<
    string,
    { scenario_name: string | null; category: string; failCount: number; lastFailedAt: string }
  >();

  for (const r of runs) {
    const existing = byScenario.get(r.scenario_id);
    if (existing) {
      existing.failCount++;
      if (r.created_at > existing.lastFailedAt) {
        existing.lastFailedAt = r.created_at;
      }
    } else {
      byScenario.set(r.scenario_id, {
        scenario_name: r.scenario_name,
        category: r.category,
        failCount: 1,
        lastFailedAt: r.created_at,
      });
    }
  }

  return Array.from(byScenario.entries())
    .map(([scenario_id, val]) => ({ scenario_id, ...val }))
    .sort((a, b) => b.failCount - a.failCount);
}

/**
 * Get live AI quality metrics for the most recent N days.
 * Used for the "Live Traffic Quality" section of the dashboard.
 */
export async function getAiQualityMetrics(
  days = 30
): Promise<AiQualityMetrics[]> {
  const supabase = await createClient();
  const dateFrom = new Date(
    Date.now() - days * 24 * 60 * 60 * 1000
  )
    .toISOString()
    .split("T")[0];

  const { data, error } = await supabase
    .from("ai_quality_metrics")
    .select("*")
    .gte("metric_date", dateFrom)
    .order("metric_date", { ascending: true });

  if (error) throw error;
  return (data || []) as AiQualityMetrics[];
}

/**
 * Get the latest AI quality metrics snapshot.
 */
export async function getLatestAiQualityMetrics(): Promise<AiQualityMetrics | null> {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from("ai_quality_metrics")
    .select("*")
    .order("metric_date", { ascending: false })
    .limit(1)
    .single();
  if (error) return null;
  return data as AiQualityMetrics;
}

// ---------------------------------------------------------------------------
// Live production stats — computed from ai_conversations when the
// ai_quality_metrics table has no data yet. This gives a real-time view of
// how the AI bot is performing with actual customers.
// ---------------------------------------------------------------------------

export type AiProductionStats = {
  totalConversations: number;
  uniqueCustomers: number;
  totalMessages: number;
  userMessages: number;
  assistantMessages: number;
  toolMessages: number;
  responseRate: number; // % of user messages that got an assistant reply
  noReplyCount: number; // unique customers with user messages but 0 assistant replies
  toolCallCount: number;
  leadStatusCounts: Record<string, number>;
  closedCount: number;
  lostCount: number;
  activeLeads: number;
  quoteGeneratedCount: number;
  handoverCount: number;
  closeAttemptCount: number;
  fallbackCount: number;
  periodStart: string | null;
  periodEnd: string | null;
};

/**
 * Compute live AI production quality stats from the ai_conversations table.
 * This mirrors the ai_quality_metrics schema but is computed on-the-fly so
 * we have data even before the metrics aggregation job runs.
 *
 * IMPORTANT: Filters out test phone numbers (2790000xxx) so only real customer
 * conversations are counted. Lead status is only counted from user/assistant
 * messages, not tool messages (tool messages are internal logs).
 */
export async function getAiProductionStats(): Promise<AiProductionStats> {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from("ai_conversations")
    .select("id, phone_number, role, lead_status, tool_calls, tool_results, message_text, created_at, conversation_metadata");

  if (error) throw error;

  const allRows = (data || []) as Array<{
    id: string;
    phone_number: string;
    role: string | null;
    lead_status: string | null;
    tool_calls: Record<string, unknown> | null;
    tool_results: Record<string, unknown> | null;
    message_text: string | null;
    created_at: string;
    conversation_metadata: Record<string, unknown> | null;
  }>;

  // Filter out test numbers and invalid phone numbers.
  // Test harness numbers start with 2790000. Other test/fake numbers
  // (empty, "unknown", all-zeros, sequential) are also filtered.
  // Additionally, phone numbers that ONLY have "tool" role messages (no
  // user or assistant messages) are internal test data, not real conversations.
  const isTestOrInvalidPhone = (phone: string) => {
    if (!phone || phone.length < 10) return true;
    if (phone === "unknown") return true;
    if (phone.startsWith("2790000")) return true;
    // All-zeros or mostly zeros (e.g. 27000000000, 27600000000)
    if (/^2\d?0{6,}$/.test(phone)) return true;
    // Sequential digits (e.g. 27123456789, 27821234567)
    if (/012345678|12345678|23456789/.test(phone)) return true;
    return false;
  };

  // First pass: identify phone numbers that have at least one user or assistant message
  const phonesWithConversation = new Set<string>();
  for (const r of allRows) {
    if ((r.role === "user" || r.role === "assistant") && !isTestOrInvalidPhone(r.phone_number)) {
      phonesWithConversation.add(r.phone_number);
    }
  }

  // Only include rows for phones that have real conversations
  const rows = allRows.filter((r) => phonesWithConversation.has(r.phone_number));

  const uniquePhones = new Set<string>();
  const phonesWithUserMsg = new Set<string>();
  const phonesWithAssistantReply = new Set<string>();
  // Track lead status per phone (use the latest non-tool message's status)
  const phoneLeadStatus: Map<string, { status: string; created_at: string }> = new Map();
  let userMessages = 0;
  let assistantMessages = 0;
  let toolMessages = 0;
  let toolCallCount = 0;
  let quoteGeneratedCount = 0;
  let handoverCount = 0;
  let closeAttemptCount = 0;
  let fallbackCount = 0;
  let periodStart: string | null = null;
  let periodEnd: string | null = null;

  for (const r of rows) {
    uniquePhones.add(r.phone_number);

    if (r.created_at && (!periodStart || r.created_at < periodStart)) {
      periodStart = r.created_at;
    }
    if (r.created_at && (!periodEnd || r.created_at > periodEnd)) {
      periodEnd = r.created_at;
    }

    if (r.role === "user") {
      userMessages++;
      phonesWithUserMsg.add(r.phone_number);
    } else if (r.role === "assistant") {
      assistantMessages++;
      phonesWithAssistantReply.add(r.phone_number);
    } else if (r.role === "tool") {
      toolMessages++;
    }

    // Count tool calls from tool role messages (tool_calls column is typically null,
    // but tool role messages indicate a tool was invoked)
    if (r.role === "tool") {
      toolCallCount++;
    }
    // Detect quote generation — check all signals but only count once per row
    let rowIndicatesQuote = false;
    if (r.tool_calls) {
      const tcStr = JSON.stringify(r.tool_calls).toLowerCase();
      if (tcStr.includes("generate_quote") || tcStr.includes("quote")) {
        rowIndicatesQuote = true;
      }
    }
    if (!rowIndicatesQuote && r.tool_results) {
      const trStr = JSON.stringify(r.tool_results).toLowerCase();
      if (trStr.includes("generate_quote") || trStr.includes("quote_id") || trStr.includes("quote_total")) {
        rowIndicatesQuote = true;
      }
    }
    if (!rowIndicatesQuote && r.role === "assistant" && r.message_text) {
      const text = r.message_text.toLowerCase();
      if (/quote\s*id[:\s]|q-\d{8}/.test(text)) {
        rowIndicatesQuote = true;
      }
    }
    if (rowIndicatesQuote) quoteGeneratedCount++;

    // Track lead status only from user/assistant messages (not tool messages)
    if (r.lead_status && (r.role === "user" || r.role === "assistant")) {
      const existing = phoneLeadStatus.get(r.phone_number);
      if (!existing || new Date(r.created_at) > new Date(existing.created_at)) {
        phoneLeadStatus.set(r.phone_number, {
          status: r.lead_status,
          created_at: r.created_at,
        });
      }
    }

    // Count fallback from metadata (handover/close_attempt are derived from
    // lead_status below to avoid double-counting)
    if (r.conversation_metadata) {
      const meta = r.conversation_metadata;
      if (meta.fallback) fallbackCount++;
    }
  }

  // Build lead status counts from per-phone latest status.
  // handoverCount and closeAttemptCount are derived solely from lead_status
  // to avoid double-counting with conversation_metadata signals above.
  const leadStatusCounts: Record<string, number> = {};
  for (const { status } of phoneLeadStatus.values()) {
    leadStatusCounts[status] = (leadStatusCounts[status] || 0) + 1;
    if (status === "handover") handoverCount++;
    if (status === "closing") closeAttemptCount++;
  }

  // no-reply = customers who sent user messages but never got an assistant reply
  let noReplyCount = 0;
  for (const phone of phonesWithUserMsg) {
    if (!phonesWithAssistantReply.has(phone)) noReplyCount++;
  }

  const responseRate =
    phonesWithUserMsg.size > 0
      ? Math.round(((phonesWithUserMsg.size - noReplyCount) / phonesWithUserMsg.size) * 100)
      : 0;

  const closedCount = leadStatusCounts["closed"] || 0;
  const lostCount = leadStatusCounts["lost"] || 0;
  const activeLeads = uniquePhones.size - closedCount - lostCount;

  return {
    totalConversations: rows.length,
    uniqueCustomers: uniquePhones.size,
    totalMessages: userMessages + assistantMessages + toolMessages,
    userMessages,
    assistantMessages,
    toolMessages,
    responseRate,
    noReplyCount,
    toolCallCount,
    leadStatusCounts,
    closedCount,
    lostCount,
    activeLeads,
    quoteGeneratedCount,
    handoverCount,
    closeAttemptCount,
    fallbackCount,
    periodStart,
    periodEnd,
  };
}

// ---------------------------------------------------------------------------
// AI Performance Score — composite score (0-100) with letter grade.
// Combines test suite pass rate with live production quality signals.
// ---------------------------------------------------------------------------

export type AiPerformanceScore = {
  score: number; // 0-100
  grade: "A" | "B" | "C" | "D" | "F";
  label: string;
  testPassRate: number | null; // % from latest test run, null if no runs
  testWeight: number; // weight applied (0-100)
  productionResponseRate: number; // % from live conversations
  productionWeight: number;
  hasTestData: boolean;
  hasProductionData: boolean;
  components: Array<{
    name: string;
    value: number;
    target: number;
    weight: number;
    contribution: number;
    passing: boolean;
  }>;
};

export async function getAiPerformanceScore(): Promise<AiPerformanceScore> {
  const [latestRun, prodStats] = await Promise.all([
    getLatestAiTestRunSummary(),
    getAiProductionStats(),
  ]);

  const components: AiPerformanceScore["components"] = [];
  let score = 0;
  let totalWeight = 0;

  // Component 1: Test suite pass rate (weight 40 if data exists, else 0)
  const hasTestData = latestRun !== null;
  const testPassRate = latestRun ? latestRun.pass_rate : null;
  const testTarget = 90; // 90% pass rate target
  if (hasTestData && testPassRate !== null) {
    const weight = 40;
    const contribution = Math.min(100, (testPassRate / testTarget) * 100) * (weight / 100);
    score += contribution;
    totalWeight += weight;
    components.push({
      name: "Test Suite Pass Rate",
      value: testPassRate,
      target: testTarget,
      weight,
      contribution: Math.round(contribution),
      passing: testPassRate >= testTarget,
    });
  }

  // Component 2: Production response rate (weight 30 if production data)
  const hasProductionData = prodStats.uniqueCustomers > 0;
  const responseTarget = 80; // 80% of customers who message should get a reply
  if (hasProductionData) {
    const weight = 30;
    const contribution =
      Math.min(100, (prodStats.responseRate / responseTarget) * 100) * (weight / 100);
    score += contribution;
    totalWeight += weight;
    components.push({
      name: "Customer Response Rate",
      value: prodStats.responseRate,
      target: responseTarget,
      weight,
      contribution: Math.round(contribution),
      passing: prodStats.responseRate >= responseTarget,
    });

    // Component 3: Lead progression (weight 15) — what % of leads moved past "new"
    const progressedLeads =
      prodStats.uniqueCustomers -
      (prodStats.leadStatusCounts["new"] || 0);
    const progressionRate =
      prodStats.uniqueCustomers > 0
        ? Math.round((progressedLeads / prodStats.uniqueCustomers) * 100)
        : 0;
    const progTarget = 50;
    const progWeight = 15;
    const progContribution =
      Math.min(100, (progressionRate / progTarget) * 100) * (progWeight / 100);
    score += progContribution;
    totalWeight += progWeight;
    components.push({
      name: "Lead Progression Rate",
      value: progressionRate,
      target: progTarget,
      weight: progWeight,
      contribution: Math.round(progContribution),
      passing: progressionRate >= progTarget,
    });

    // Component 4: Quote generation activity (weight 15) — tool calls producing quotes
    const quoteRate =
      prodStats.uniqueCustomers > 0
        ? Math.round((prodStats.quoteGeneratedCount / prodStats.uniqueCustomers) * 100)
        : 0;
    const quoteTarget = 30;
    const quoteWeight = 15;
    const quoteContribution =
      Math.min(100, (quoteRate / quoteTarget) * 100) * (quoteWeight / 100);
    score += quoteContribution;
    totalWeight += quoteWeight;
    components.push({
      name: "Quote Generation Rate",
      value: quoteRate,
      target: quoteTarget,
      weight: quoteWeight,
      contribution: Math.round(quoteContribution),
      passing: quoteRate >= quoteTarget,
    });
  }

  // Normalize score to 0-100 based on weights actually used
  const finalScore = totalWeight > 0 ? Math.round((score / totalWeight) * 100) : 0;

  let grade: AiPerformanceScore["grade"] = "F";
  let label = "No data";
  if (totalWeight > 0) {
    if (finalScore >= 90) {
      grade = "A";
      label = "Excellent";
    } else if (finalScore >= 80) {
      grade = "B";
      label = "Good";
    } else if (finalScore >= 70) {
      grade = "C";
      label = "Needs Improvement";
    } else if (finalScore >= 60) {
      grade = "D";
      label = "Below Standard";
    } else {
      grade = "F";
      label = "Failing";
    }
  }

  return {
    score: finalScore,
    grade,
    label,
    testPassRate,
    testWeight: hasTestData ? 40 : 0,
    productionResponseRate: prodStats.responseRate,
    productionWeight: hasProductionData ? 60 : 0,
    hasTestData,
    hasProductionData,
    components,
  };
}

// ---------------------------------------------------------------------------
// Phase 2b: Live Conversation Quality Tracking
// ---------------------------------------------------------------------------

/**
 * Get recent conversations grouped by phone number with quality flags.
 * Each row represents one customer's conversation thread with quality scoring.
 */
export async function getRecentConversationSummaries(
  limit = 20
): Promise<ConversationSummary[]> {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from("ai_conversations")
    .select(
      "id, phone_number, sender_name, role, message_text, lead_status, customer_type, quote_id, quote_total, tool_calls, tool_results, conversation_metadata, created_at"
    )
    .order("created_at", { ascending: false })
    .limit(500); // fetch recent batch, group in memory

  if (error) throw error;

  // Filter out test numbers and invalid phone numbers (same logic as getAiProductionStats)
  const isTestOrInvalidPhone = (phone: string) => {
    if (!phone || phone.length < 10) return true;
    if (phone === "unknown") return true;
    if (phone.startsWith("2790000")) return true;
    if (/^2\d?0{6,}$/.test(phone)) return true;
    if (/012345678|12345678|23456789/.test(phone)) return true;
    return false;
  };

  // Only include phones that have at least one user or assistant message
  const phonesWithConversation = new Set<string>();
  for (const r of (data || [])) {
    const row = r as { phone_number: string; role: string | null };
    if ((row.role === "user" || row.role === "assistant") && !isTestOrInvalidPhone(row.phone_number)) {
      phonesWithConversation.add(row.phone_number);
    }
  }

  const rows = ((data || []) as Array<{
    id: string;
    phone_number: string;
    sender_name: string | null;
    role: string | null;
    message_text: string | null;
    lead_status: string | null;
    customer_type: string | null;
    quote_id: string | null;
    quote_total: number | null;
    tool_calls: Record<string, unknown> | null;
    tool_results: Record<string, unknown> | null;
    conversation_metadata: Record<string, unknown> | null;
    created_at: string;
  }>).filter((r) => phonesWithConversation.has(r.phone_number));

  // Group by phone_number
  const byPhone = new Map<string, typeof rows>();
  for (const r of rows) {
    const arr = byPhone.get(r.phone_number) || [];
    arr.push(r);
    byPhone.set(r.phone_number, arr);
  }

  const summaries: ConversationSummary[] = [];

  for (const [phone, msgs] of byPhone) {
    // Sort by created_at ascending
    msgs.sort((a, b) => new Date(a.created_at).getTime() - new Date(b.created_at).getTime());

    const userMsgs = msgs.filter((m) => m.role === "user");
    const assistantMsgs = msgs.filter((m) => m.role === "assistant");
    const toolMsgs = msgs.filter((m) => m.role === "tool");

    const firstMsg = msgs[0];
    const lastMsg = msgs[msgs.length - 1];
    const firstUserMsg = userMsgs[0];
    const firstAssistantReply = assistantMsgs[0];

    // Compute response latency (first user msg → first assistant reply)
    let responseLatencyMs: number | null = null;
    if (firstUserMsg && firstAssistantReply) {
      responseLatencyMs =
        new Date(firstAssistantReply.created_at).getTime() -
        new Date(firstUserMsg.created_at).getTime();
    }

    // Quality flags
    const flags: ConversationQualityFlag[] = [];
    const flagsSet = new Set<ConversationQualityFlag>();

    const addFlag = (f: ConversationQualityFlag) => {
      if (!flagsSet.has(f)) {
        flagsSet.add(f);
        flags.push(f);
      }
    };

    // Check if greeted (first assistant reply starts with greeting)
    if (firstAssistantReply) {
      const text = (firstAssistantReply.message_text || "").toLowerCase();
      if (/^(hi|hey|hello|welcome|good morning|good afternoon|good evening)/.test(text)) {
        addFlag("greeted");
      }
    }

    // Check if no reply
    if (userMsgs.length > 0 && assistantMsgs.length === 0) {
      addFlag("no_reply");
    }

    // Check if quoted
    const hasQuote = msgs.some(
      (m) => m.quote_id || m.quote_total || (m.tool_calls && JSON.stringify(m.tool_calls).toLowerCase().includes("generate_quote"))
    );
    if (hasQuote) addFlag("quoted");

    // Check if close attempted
    const hasCloseAttempt = msgs.some((m) => {
      if (m.conversation_metadata && (m.conversation_metadata.close_attempt || m.conversation_metadata.close_attempt_count)) {
        return true;
      }
      if (m.lead_status === "closing" || m.lead_status === "closed") return true;
      const text = (m.message_text || "").toLowerCase();
      return /shall i|can i|would you like|ready to|process.*order|confirm.*order|place.*order|go ahead/.test(text) && m.role === "assistant";
    });
    if (hasCloseAttempt) addFlag("close_attempted");

    // Check if objection handled
    const hasObjection = msgs.some((m) => {
      if (m.lead_status === "objection") return true;
      if (m.tool_results && JSON.stringify(m.tool_results).toLowerCase().includes("objection")) return true;
      return false;
    });
    if (hasObjection) addFlag("objection_handled");

    // Check if handed over
    const hasHandover = msgs.some(
      (m) => m.lead_status === "handover" || (m.tool_calls && JSON.stringify(m.tool_calls).toLowerCase().includes("handover"))
    );
    if (hasHandover) addFlag("handed_over");

    // Check if fallback was used
    const hasFallback = msgs.some((m) => {
      if (m.conversation_metadata && m.conversation_metadata.fallback) return true;
      const text = (m.message_text || "").toLowerCase();
      return /having trouble|just a sec|trouble generating|moment.*help|shortly/.test(text) && m.role === "assistant";
    });
    if (hasFallback) addFlag("fallback_used");

    // Check if image was processed
    const hasImage = msgs.some((m) => {
      if (m.conversation_metadata && m.conversation_metadata.has_image) return true;
      if (m.tool_calls && JSON.stringify(m.tool_calls).toLowerCase().includes("image")) return true;
      return false;
    });
    if (hasImage) addFlag("image_processed");

    // Compute quality score (0-100)
    let score = 0;
    if (flagsSet.has("greeted")) score += 15;
    if (!flagsSet.has("no_reply")) score += 20;
    if (flagsSet.has("quoted")) score += 25;
    if (flagsSet.has("close_attempted")) score += 20;
    if (flagsSet.has("objection_handled")) score += 10;
    if (!flagsSet.has("fallback_used")) score += 10;
    // Bonus for response speed
    if (responseLatencyMs !== null && responseLatencyMs < 15000) score += 5;
    else if (responseLatencyMs !== null && responseLatencyMs < 30000) score += 2;

    const customerName = firstMsg?.sender_name || null;
    const lastLeadStatus = lastMsg?.lead_status || null;
    const quoteId = msgs.find((m) => m.quote_id)?.quote_id || null;
    const quoteTotal = msgs.find((m) => m.quote_total)?.quote_total || null;
    const toolCallCount = msgs.filter((m) => m.tool_calls).length;

    summaries.push({
      phone_number: phone,
      customer_name: customerName,
      customer_type: lastMsg?.customer_type || null,
      message_count: msgs.length,
      user_message_count: userMsgs.length,
      assistant_message_count: assistantMsgs.length,
      first_message_at: firstMsg?.created_at || "",
      last_message_at: lastMsg?.created_at || "",
      lead_status: lastLeadStatus,
      quote_id: quoteId,
      quote_total: quoteTotal ? Number(quoteTotal) : null,
      quality_flags: flags,
      quality_score: Math.min(100, score),
      tool_call_count: toolCallCount,
      has_fallback: flagsSet.has("fallback_used"),
      response_latency_ms: responseLatencyMs,
    });
  }

  // Sort by last message time descending, take top N
  summaries.sort(
    (a, b) => new Date(b.last_message_at).getTime() - new Date(a.last_message_at).getTime()
  );

  return summaries.slice(0, limit);
}

/**
 * Get AI monitor alerts from intelligence_reports where category = 'ai_quality'.
 */
export async function getAiMonitorAlerts(
  days = 30
): Promise<AiMonitorAlert[]> {
  const supabase = await createClient();
  const dateFrom = new Date(
    Date.now() - days * 24 * 60 * 60 * 1000
  ).toISOString();
  const { data, error } = await supabase
    .from("intelligence_reports")
    .select("*")
    .eq("category", "ai_quality")
    .gte("report_date", dateFrom.split("T")[0])
    .order("created_at", { ascending: false })
    .limit(50);

  if (error) throw error;
  return (data || []) as AiMonitorAlert[];
}

/**
 * Get conversation quality trend from ai_quality_metrics.
 * Returns daily snapshots for charting.
 */
export async function getAiQualityTrend(
  days = 30
): Promise<AiQualityMetrics[]> {
  const supabase = await createClient();
  const dateFrom = new Date(
    Date.now() - days * 24 * 60 * 60 * 1000
  )
    .toISOString()
    .split("T")[0];

  const { data, error } = await supabase
    .from("ai_quality_metrics")
    .select("*")
    .gte("metric_date", dateFrom)
    .order("metric_date", { ascending: true });

  if (error) throw error;
  return (data || []) as AiQualityMetrics[];
}

// ---------------------------------------------------------------------------
// RBAC / User Management
// ---------------------------------------------------------------------------

/**
 * Lists all CRM users with their roles. Uses the admin client to read
 * auth.users (emails + ban status) and joins with user_roles.
 */
export async function listUsers(): Promise<UserWithRole[]> {
  const admin = createAdminClient();

  const {
    data: { users },
    error: usersErr,
  } = await admin.auth.admin.listUsers();

  if (usersErr) throw usersErr;

  const { data: roles, error: rolesErr } = await admin
    .from("user_roles")
    .select("user_id, role, full_name, branch_id, created_at, updated_at");

  if (rolesErr) throw rolesErr;

  const roleMap = new Map(
    (roles || []).map((r) => [r.user_id as string, r]),
  );

  return users.map((u) => {
    const r = roleMap.get(u.id);
    return {
      id: u.id,
      email: u.email ?? "",
      role: (r?.role as UserRole) ?? "sales",
      full_name: r?.full_name ?? null,
      branch_id: r?.branch_id ?? null,
      created_at: u.created_at ?? "",
      updated_at: r?.updated_at ?? "",
      banned_until: u.banned_until ?? null,
      is_active: !u.banned_until,
    };
  });
}

/**
 * Creates a new CRM user: auth.users entry + user_roles row.
 * Returns the new user's id, or throws on error.
 */
export async function createUser(input: {
  email: string;
  password: string;
  fullName: string;
  role: UserRole;
  branchId?: number | null;
}): Promise<{ id: string }> {
  const admin = createAdminClient();

  const {
    data: authData,
    error: authErr,
  } = await admin.auth.admin.createUser({
    email: input.email,
    password: input.password,
    email_confirm: true,
    user_metadata: { full_name: input.fullName },
  });

  if (authErr) throw authErr;
  const userId = authData.user.id;

  const { error: roleErr } = await admin.from("user_roles").insert({
    user_id: userId,
    role: input.role,
    full_name: input.fullName,
    branch_id: input.branchId ?? null,
  });

  if (roleErr) {
    // Best-effort cleanup: remove the auth user if role insert failed.
    await admin.auth.admin.deleteUser(userId);
    throw roleErr;
  }

  return { id: userId };
}

/**
 * Updates a user's role / name / branch. Uses admin client to bypass RLS
 * (managers are additionally constrained by the caller before reaching here).
 */
export async function updateUser(
  userId: string,
  input: { role?: UserRole; fullName?: string; branchId?: number | null },
): Promise<void> {
  const admin = createAdminClient();

  const update: Record<string, unknown> = {};
  if (input.role !== undefined) update.role = input.role;
  if (input.fullName !== undefined) update.full_name = input.fullName;
  if (input.branchId !== undefined) update.branch_id = input.branchId;

  if (Object.keys(update).length === 0) return;

  const { error } = await admin
    .from("user_roles")
    .update(update)
    .eq("user_id", userId);

  if (error) throw error;
}

/**
 * Deactivates (bans) a user so they can no longer sign in. Preserves the
 * audit trail — does not delete the auth user.
 */
export async function deactivateUser(userId: string): Promise<void> {
  const admin = createAdminClient();
  const { error } = await admin.auth.admin.updateUserById(userId, {
    ban_duration: "876000h", // ~100 years — effectively permanent
  });
  if (error) throw error;
}

/**
 * Reactivates a previously banned user.
 */
export async function reactivateUser(userId: string): Promise<void> {
  const admin = createAdminClient();
  const { error } = await admin.auth.admin.updateUserById(userId, {
    ban_duration: "none",
  });
  if (error) throw error;
}

// ============================================================================
// Product Catalog Management
// ============================================================================

export async function getProducts(): Promise<Product[]> {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from("products")
    .select("*")
    .order("name", { ascending: true });
  if (error) throw error;
  return (data || []) as Product[];
}

// ============================================================================
// Price-Objection Close Rate Funnel (#9)
// ============================================================================

export type PriceObjectionFunnel = {
  totalCustomers: number;
  objectionsRaised: number;
  quotesGenerated: number;
  closeAttempts: number;
  won: number;
  lost: number;
  // Conversion rates between stages
  objectionRate: number; // objections / total
  quoteAfterObjectionRate: number; // quotes / objections
  closeAttemptRate: number; // close attempts / quotes
  winRate: number; // won / close attempts
  // Breakdowns
  byObjectionType: { type: string; count: number }[];
  byCloseType: { type: string; count: number }[];
};

export async function getPriceObjectionFunnel(): Promise<PriceObjectionFunnel> {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from("customer_profiles")
    .select(
      "id, objection_count, close_attempt_count, last_close_type, sale_outcome, total_quotes, objections, do_not_contact"
    )
    .or("do_not_contact.is.false,do_not_contact.is.null");
  if (error) throw error;

  const customers = (data || []) as Array<{
    id: string;
    objection_count: number;
    close_attempt_count: number;
    last_close_type: string | null;
    sale_outcome: string | null;
    total_quotes: number;
    objections: string[] | null;
    do_not_contact: boolean | null;
  }>;

  const totalCustomers = customers.length;
  const objectionsRaised = customers.filter(
    (c) => (c.objection_count || 0) > 0
  ).length;
  const quotesGenerated = customers.filter(
    (c) => (c.total_quotes || 0) > 0
  ).length;
  const closeAttempts = customers.filter(
    (c) => (c.close_attempt_count || 0) > 0
  ).length;
  const won = customers.filter((c) => c.sale_outcome === "won").length;
  const lost = customers.filter((c) => c.sale_outcome === "lost").length;

  // Breakdown by objection type
  const objectionTypeCounts = new Map<string, number>();
  for (const c of customers) {
    if (c.objections && c.objections.length > 0) {
      for (const o of c.objections) {
        const key = o || "unknown";
        objectionTypeCounts.set(key, (objectionTypeCounts.get(key) || 0) + 1);
      }
    }
  }
  const byObjectionType = Array.from(objectionTypeCounts.entries())
    .map(([type, count]) => ({ type, count }))
    .sort((a, b) => b.count - a.count);

  // Breakdown by close type
  const closeTypeCounts = new Map<string, number>();
  for (const c of customers) {
    if (c.last_close_type) {
      closeTypeCounts.set(
        c.last_close_type,
        (closeTypeCounts.get(c.last_close_type) || 0) + 1
      );
    }
  }
  const byCloseType = Array.from(closeTypeCounts.entries())
    .map(([type, count]) => ({ type, count }))
    .sort((a, b) => b.count - a.count);

  return {
    totalCustomers,
    objectionsRaised,
    quotesGenerated,
    closeAttempts,
    won,
    lost,
    objectionRate:
      totalCustomers > 0
        ? Math.round((objectionsRaised / totalCustomers) * 100)
        : 0,
    quoteAfterObjectionRate:
      objectionsRaised > 0
        ? Math.round((quotesGenerated / objectionsRaised) * 100)
        : 0,
    closeAttemptRate:
      quotesGenerated > 0
        ? Math.round((closeAttempts / quotesGenerated) * 100)
        : 0,
    winRate:
      closeAttempts > 0 ? Math.round((won / closeAttempts) * 100) : 0,
    byObjectionType,
    byCloseType,
  };
}
