import { QuotesTabs } from "@/components/quotes-tabs";
import { getChatbotQuotes, getChatbotQuoteAcceptance } from "@/lib/queries";
import {
  Card,
  CardContent,
} from "@/components/ui/card";

export default async function QuotesPage() {
  const chatbotQuotes = await getChatbotQuotes();
  const acceptance = await getChatbotQuoteAcceptance(chatbotQuotes);
  const acceptedCount = Object.values(acceptance).filter((a) => a.accepted).length;

  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-2xl font-heading font-bold">Quotes</h1>
        <p className="text-sm text-muted-foreground mt-1">
          Quotes generated by the WhatsApp AI chatbot
        </p>
      </div>

      {chatbotQuotes.length > 0 ? (
        <QuotesTabs
          quotes={chatbotQuotes}
          acceptance={acceptance}
          acceptedCount={acceptedCount}
        />
      ) : (
        <Card>
          <CardContent className="p-8 text-center text-muted-foreground">
            No chatbot quotes yet. They will appear here once the chatbot generates them.
          </CardContent>
        </Card>
      )}
    </div>
  );
}
