import { QuotesTable } from "@/components/quotes-table";
import { getChatbotQuotes } from "@/lib/queries";
import {
  Card,
  CardContent,
} from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

export default async function QuotesPage() {
  const chatbotQuotes = await getChatbotQuotes();

  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-2xl font-heading font-bold">Quotes</h1>
        <p className="text-sm text-muted-foreground mt-1">
          Quotes generated by the WhatsApp AI chatbot
        </p>
      </div>

      {/* Chatbot Quotes */}
      <div className="space-y-4">
        <div className="flex items-center gap-2">
          <h2 className="text-lg font-heading font-semibold">Chatbot Quotes</h2>
          <Badge className="bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200">
            {chatbotQuotes.length} quotes
          </Badge>
        </div>
        {chatbotQuotes.length > 0 ? (
          <QuotesTable quotes={chatbotQuotes} />
        ) : (
          <Card>
            <CardContent className="p-8 text-center text-muted-foreground">
              No chatbot quotes yet. They will appear here once the chatbot generates them.
            </CardContent>
          </Card>
        )}
      </div>
    </div>
  );
}
