import { QuotesTable } from "@/components/quotes-table";
import { getChatbotQuotes, getChatbotQuoteAcceptance } from "@/lib/queries";
import {
  Card,
  CardContent,
} from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

export default async function QuotesPage() {
  const chatbotQuotes = await getChatbotQuotes();
  const acceptance = await getChatbotQuoteAcceptance(chatbotQuotes);
  const acceptedCount = Object.values(acceptance).filter((a) => a.accepted).length;

  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-2xl font-heading font-bold">Quotes</h1>
        <p className="text-sm text-muted-foreground mt-1">
          Quotes generated by the WhatsApp AI chatbot
        </p>
      </div>

      {/* Chatbot Quotes */}
      <div className="space-y-4">
        <div className="flex items-center gap-2">
          <h2 className="text-lg font-heading font-semibold">Chatbot Quotes</h2>
          <Badge className="bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200">
            {chatbotQuotes.length} quotes
          </Badge>
          {chatbotQuotes.length > 0 && (
            <Badge variant="outline" className="border-emerald-300 text-emerald-700 dark:border-emerald-700 dark:text-emerald-300">
              {acceptedCount} customer-accepted
            </Badge>
          )}
        </div>
        {chatbotQuotes.length > 0 ? (
          <QuotesTable quotes={chatbotQuotes} acceptance={acceptance} />
        ) : (
          <Card>
            <CardContent className="p-8 text-center text-muted-foreground">
              No chatbot quotes yet. They will appear here once the chatbot generates them.
            </CardContent>
          </Card>
        )}
      </div>
    </div>
  );
}
